spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_oauth2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none